### ISSUE TITLE
欢迎留言，看到必回

### ISSUE THREAD

**Issue by LiangJunrong** [LiangJunrong/document-library#3]
欢迎小伙伴们提供建议/意见。
如果小伙伴对某个知识点有自己的理解，觉得应该让更多小伙伴知道，可以联系 jsliang。
如果小伙伴存在疑问，想探讨一二，可以留言或者加 QQ 咨询。

个人 QQ：1741020489

**Comment by XGHeaven** [comment]
大佬还是学生么？

顺便说一句，**不用 mac 的前端，跟咸鱼有什么区别**，**用不起 mac 的前端，不用 linux 跟咸鱼有什么区别**，**不用 telegram 的前端，跟咸鱼有什么区别**。

(手动滑稽)

**Comment by LiangJunrong** [comment]
> 大佬还是学生么？
> 
> 顺便说一句，**不用 mac 的前端，跟咸鱼有什么区别**，**用不起 mac 的前端，不用 linux 跟咸鱼有什么区别**，**不用 telegram 的前端，跟咸鱼有什么区别**。
> 
> (手动滑稽)

可以可以，优秀，明年 5 月工作一年了。等跳槽了再换 Mac 吧

**Comment by XGHeaven** [comment]
哈哈哈，早换早享受呀。

**Comment by LienJack** [comment]
恭喜大佬star666 特此记录留念

**Comment by LiangJunrong** [comment]
> 恭喜大佬star666 特此记录留念

哈哈哈，谢谢！

**Comment by justin-init** [comment]
老哥很给力啊

**Comment by LiangJunrong** [comment]
> 老哥很给力啊

还是要不断加油，要不然真的比不上应届生了
