### ISSUE TITLE
this指向中【8.3 箭头函数的 this】答案错了

### ISSUE THREAD

**Issue by Auroka** [LiangJunrong/document-library#59]
https://github.com/LiangJunrong/document-library/blob/master/%E7%B3%BB%E5%88%97-%E9%9D%A2%E8%AF%95%E8%B5%84%E6%96%99/JavaScript/this.md#83-%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0%E7%9A%84-this

**Comment by LiangJunrong** [comment]
感谢提示，已修复~
