### ISSUE TITLE
留言板 · jsliang 的文档库

### ISSUE THREAD

**Issue by LiangJunrong** [LiangJunrong/document-library#6]
https://liangjunrong.github.io/MessageBoard.html

**Comment by LiangJunrong** [comment]
不折腾的前端，和咸鱼有什么区别！

**Comment by hu-qi** [comment]
梁sir，OK啦！
--- 来自本地提交

**Comment by MARPTS** [comment]
> @LiangJunrong
> 不折腾的前端，和咸鱼有什么区别！

good！

**Comment by LiangJunrong** [comment]
> > @LiangJunrong
> > 不折腾的前端，和咸鱼有什么区别！
> 
> good！

加油

**Comment by LiangJunrong** [comment]
> 梁sir，OK啦！
> --- 来自本地提交

好的，谢谢

**Comment by justin-init** [comment]
种下一棵树最好的时间是十年前，其次是现在。

**Comment by LiangJunrong** [comment]
> @teachat8
> 种下一棵树最好的时间是十年前，其次是现在。

精辟

**Comment by livaha** [comment]
留言板是在这里（issue）提问的？
留言板怎么做的哟

**Comment by hu-qi** [comment]
> 留言板是在这里（issue）提问的？
> 留言板怎么做的哟

[gitalk](https://github.com/gitalk/gitalk) 了解一下
请参考https://liangjunrong.github.io/other-library/Markdown-Websites/GitBook/GitBook-study.html#%E6%8F%92%E4%BB%B6-13---gitalk

**Comment by livaha** [comment]
好玩

**Comment by livaha** [comment]
> > 留言板是在这里（issue）提问的？
> > 留言板怎么做的哟
> 
> [gitalk](https://github.com/gitalk/gitalk) 了解一下
> 请参考https://liangjunrong.github.io/other-library/Markdown-Websites/GitBook/GitBook-study.html#%E6%8F%92%E4%BB%B6-13---gitalk

哈哈看会了，谢谢哦

**Comment by livaha** [comment]
有意思

**Comment by LiangJunrong** [comment]
> 有意思

加油，一起折腾，啊哈哈
