### ISSUE TITLE
变量文档存在一些问题，具体看下面

### ISSUE THREAD

**Issue by xyyojl** [LiangJunrong/document-library#62]
文档链接：https://github.com/LiangJunrong/document-library/blob/master/%E7%B3%BB%E5%88%97-%E9%9D%A2%E8%AF%95%E8%B5%84%E6%96%99/JavaScript/%E5%8F%98%E9%87%8F.md
### 5.3 题目 2 
输出结果：[Function: a] 100 报错：Uncaught TypeError: a is not a function
![image](https://user-images.githubusercontent.com/32906942/106993720-42f51980-67b6-11eb-9930-62d8972f3706.png)

### 5.6 题目 5
题目中的自执行函数没有 var foo; 但是答案里面的自执行函数有 var foo;
![image](https://user-images.githubusercontent.com/32906942/106993810-7e8fe380-67b6-11eb-8985-43ef83dfc0fa.png)

**Comment by LiangJunrong** [comment]
> 文档链接：https://github.com/LiangJunrong/document-library/blob/master/%E7%B3%BB%E5%88%97-%E9%9D%A2%E8%AF%95%E8%B5%84%E6%96%99/JavaScript/%E5%8F%98%E9%87%8F.md
> 
> ### 5.3 题目 2
> 输出结果：[Function: a] 100 报错：Uncaught TypeError: a is not a function
> ![image](https://user-images.githubusercontent.com/32906942/106993720-42f51980-67b6-11eb-9930-62d8972f3706.png)
> 
> ### 5.6 题目 5
> 题目中的自执行函数没有 var foo; 但是答案里面的自执行函数有 var foo;
> ![image](https://user-images.githubusercontent.com/32906942/106993810-7e8fe380-67b6-11eb-8985-43ef83dfc0fa.png)

感谢纠正，已合并
